#!/bin/bash

pwd

REMOTE_WORKHORSE_USER="zeus"
REMOTE_WORKHORSE_IP="192.168.1.2"
REMOTE_WORKHORSE_PATH="~/Documents/NaVid-VLN-CE/output/"
LOCAL_PATH="out.jpg"

# rsync "$LOCAL_PATH" "$REMOTE_WORKHORSE_USER@$REMOTE_WORKHORSE_IP:$REMOTE_WORKHORSE_PATH"
rsync "$LOCAL_PATH" "$REMOTE_WORKHORSE_USER:$REMOTE_WORKHORSE_PATH"
